### ISSUE TITLE
This is supported by Now CLI

### ISSUE THREAD

**Issue by sergiodxa** [matiastucci/now-purge#5]
The feature of this module is now supported directly by Now CLI in a single command:

```bash
now rm <app> --safe
```

> It will remove all the deployments of the given app without an assigned alias.

However, some users still recommend it, maybe is a good idea to mention it in the README?

**Comment by matiastucci** [comment]
Cool.

Is it possible to purge the instances of _all_ the apps?

**Comment by sergiodxa** [comment]
All apps at the same time no, only per app.
